=== Antoniouis/lenguaje-de-marcas/PARTE_04/Ejercicio_35_Proyecto_Final_Parte4/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="year" type="xs:gYear"/>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="category" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Antoniouis/lenguaje-de-marcas/PARTE_04/Ejercicio_35_Proyecto_Final_Parte4/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="schema.xsd">

    <item category="fiction">
        <title>El Señor de los Anillos</title>
        <author>J.R.R. Tolkien</author>
        <year>1954</year>
        <description>Una épica aventura de fantasía.</description>
    </item>

    <item category="science">
        <title>Breves respuestas a las grandes preguntas</title>
        <author>Stephen Hawking</author>
        <year>2018</year>
        <description>Reflexiones sobre el universo.</description>
    </item>

    <item category="history">
        <title>Sapiens</title>
        <author>Yuval Noah Harari</author>
        <year>2011</year>
        <description>Historia de la humanidad.</description>
    </item>

</catalog>
